path: /root/datasets/all_parameters_SAHI_640_classesall_max_samples2000
nc: 3
names:
  - standing_player
  - football
  - goal
dataset_name: football_detection_all_parameters
train: images/train
val: images/val
test: images/test
test_original: images/test-original
